### PR TITLE
Add Bob exercise

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by paf31** [comment]
Looks good, thanks, but I wonder if we should encourage using more idiomatic functions instead of regex: `isSuffixOf "?"`, `any isAlpha`, etc.

**Comment by lpil** [comment]
I'm not a Purescript or Haskell person so I would really appreciate feedback on how I can make the solutions more idiomatic :)

**Comment by paf31** [comment]
I don't think there's anything _wrong_ with the regex solutions per se, just that we could illustrate the use of some fairly standard functions instead.

But this is probably good as an initial version. We can always change the example later, as a non-breaking change, right?

**Comment by lpil** [comment]
Sure, but I'm happy to make the change now in this instance. I need to learn the standard library more anyway.

**Comment by paf31** [comment]
I would probably use 

- `isSuffixOf "?"`
- `toCharArray >>> any isAlpha`
- `toCharArray >>> all isSpace`

These are slower but express the intent more, I think.

So it's really a question of what the use case is, but since the use case here is learning PureScript, I think I prefer the expressive version 😄

**Comment by lpil** [comment]
I couldn't find `isSuffixOf` anywhere. Are you suggesting I implement it?

**Comment by paf31** [comment]
Sorry, I was thinking of Haskell, although we do have `stripSuffix`. You could maybe use `lastIndexOf`, but it's probably more trouble than it's worth.

Maybe let's leave this as a regex for now then?

**Comment by lpil** [comment]
Sure, I'll move onto the next one :)

**Comment by lpil** [comment]
Also is it normal for the test's main function to have type sigs like this?

```purescript
main :: forall e. Eff ( timer :: TIMER
                      , avar :: AVAR
                      , console :: CONSOLE
                      , random :: RANDOM
                      , testOutput :: TESTOUTPUT | e
                      ) Unit
```

Seems very verbose.

**Comment by paf31** [comment]
Yes, but you could have it inferred by using a type wildcard if you prefer:

```
main :: Eff _ Unit
```

**Comment by lpil** [comment]
ooh, thanks!

**Comment by lpil** [comment]
Good to merge this? :)

**Comment by paf31** [comment]
Yes, sorry for the delay.

**Pull request merged**
