### PR TITLE
Added support for Travis cache (issue #23)

### PR DESCRIPTION
**Pull request by icyrockcom**
Pull request for https://github.com/exercism/xpurescript/issues/23

### CODE REVIEW

**Comment by paf31** [comment]
@lpil Are you familiar with this code?

**Comment by lpil** [comment]
The original script is an adaption of one I pinched from (I think) the Haskell repo. The changes look good to me. :)

I wonder if it's possible to share the common deps so they don't need to be compiled for each project.

**Comment by icyrockcom** [comment]
@lpil 

> I wonder if it's possible to share the common deps so they don't need to be compiled for each project. Probably one for a later PR.

If you meant sharing `bower_components` folders, yes it is possible. The only reason I did not do that is due to the fact that bower uses flat dependencies. In case two exercises use different versions of the same dependency, this could result in problems. On the other hand, the probability of that happening is probably low.

However, that would probably not result in significant improvements over time - after the first download and compilation of a single exercise, the whole thing is cached, so it would not recompile in subsequent builds.

In any case, let me know if you'd prefer me to change to that model.

**Comment by lpil** [comment]
I think the current approach is good :)

**Comment by icyrockcom** [comment]
@paf31 Do you think this can be merged at this point or do you suggest any additional changes?

**Comment by paf31** [comment]
Thanks!

**Comment by icyrockcom** [comment]
That was quick, thanks @paf31!

**Pull request merged**
